# @baseUrl = https://financeiro-back.onrender.com
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "admin@admin.com",
	"password": "admin"
}

###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"email": "matheus@admin.com",
	"name": "Matheus Gabriel",
	"password": "Fazendeiro1!"
}

###

#! Saldo

# @name amount
GET {{baseUrl}}/amount
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

#! Categorias

# @name list_categories
GET {{baseUrl}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_category
POST {{baseUrl}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Salario",
	"description": "Pagamento salario"
}

###

#! Transactions

# @name list_transactions
GET {{baseUrl}}/transaction
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_transaction
POST {{baseUrl}}/transaction
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"message": "Banco",
	"value": 20.20,
	"categories": ["fa917ff4-20ef-4022-8adc-6764bfcf28e6"],
	"type": "PAY"
}

###

#! Debt

# @name list_debt
GET {{baseUrl}}/debt
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_debt
POST {{baseUrl}}/debt
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Gazin",
	"description": "pagamento da gazin",
	"instalments": [
		{
			"value": 100,
			"status": "SCHEDULE",
			"date": "2025-01-15"
		}
	]
}

###

# @name delete_debt
DELETE {{baseUrl}}/debt/ec748c68-e06b-4159-9522-582e8067dc26
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

#! Installment

# @name list_installment
GET {{baseUrl}}/installment?month=2&year=2025
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name pay_installment
PATCH {{baseUrl}}/installment/56f36178-8e09-4bbf-8e09-ede6f61b3762
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name crete_installment
POST {{baseUrl}}/installment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"value": 99,
	"debtId": "781de4a3-f464-467f-acfa-a075c4d26926",
	"date": "2025-02-15"
}

###

# @name delete_installment
DELETE {{baseUrl}}/installment/18f5c807-a19e-4422-bb53-c5bf26b69e3f
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
