@baseUrl = https://financeiro-back.onrender.com
# @baseUrl = http://192.168.1.106:3333
@authToken = {{authenticate.response.body.access_token}}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "admin@admin.com",
	"password": "admin"
}

###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"email": "admin@admin.com",
	"name": "Matheus Gabriel",
	"password": "admin"
}

###

#! Saldo

# @name amount
GET {{baseUrl}}/amount
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name details
GET {{baseUrl}}/details
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name details_filtered
GET {{baseUrl}}/details?month=3&year=2025
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name details_annual_projection
GET {{baseUrl}}/details/projection
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name details_annual_projection_filtered
GET {{baseUrl}}/details/projection?year=2025
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

#! Entradas Recorrentes

# @name list_recurring_incomes
GET {{baseUrl}}/recurring-income
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name create_recurring_income
POST {{baseUrl}}/recurring-income
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Salário",
	"value": 3500,
	"dayOfMonth": 5
}
###

# @name delete_recurring_income
DELETE {{baseUrl}}/recurring-income/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

#! Pagamentos Recorrentes

# @name list_recurring_payments
GET {{baseUrl}}/recurring-payment
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name create_recurring_payment
POST {{baseUrl}}/recurring-payment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Aluguel",
	"value": 1200,
	"dayOfMonth": 10
}
###

# @name pay_recurring_payment
POST {{baseUrl}}/recurring-payment/00000000-0000-0000-0000-000000000000/pay
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name delete_recurring_payment
DELETE {{baseUrl}}/recurring-payment/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

#! Categorias

# @name list_categories
GET {{baseUrl}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_category
POST {{baseUrl}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Salario",
	"description": "Pagamento salario"
}

###

# @name delete_category
DELETE {{baseUrl}}/category/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

#! Transactions

# @name list_transactions
GET {{baseUrl}}/transaction
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_transaction
POST {{baseUrl}}/transaction
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"message": "Banco",
	"value": 20.20,
	"type": "PAY"
}

###

#! Debt

# @name list_debts
GET {{baseUrl}}/debt
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name list_debt
GET {{baseUrl}}/debt/9821854d-9b12-4a5e-9522-a9cc8e0bc159
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_debt
POST {{baseUrl}}/debt
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Gazin 2",
	"description": "pagamento da gazin 2",
	"installments": [
		{
			"value": 100,
			"status": "SCHEDULE",
			"date": "2025-20-20"
		}
	]
}

###

# @name create_debt_recurrence
POST {{baseUrl}}/debt/recurrence
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Gazin 2",
	"description": "pagamento da gazin 2",
	"value": 100,
	"installmentsCount": 10,
	"dayOfMonth": "15",
	"recurrence": "MONTHLY"
}

###

# @name delete_debt
DELETE {{baseUrl}}/debt/ec748c68-e06b-4159-9522-582e8067dc26
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

#! Installment

# @name list_installment
GET {{baseUrl}}/installment?month=3&year=2026
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name pay_installment
PATCH {{baseUrl}}/installment/329ac95a-e6e4-485f-a344-2481575a4f6c
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name crete_installment
POST {{baseUrl}}/installment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"value": 99,
	"debtId": "f588a152-28b8-48a2-a0a3-e925484d32e1",
	"date": "2025-02-20"
}

###

# @name delete_installment
DELETE {{baseUrl}}/installment/18f5c807-a19e-4422-bb53-c5bf26b69e3f
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

#! Compras Futuras

# @name list_future_purchases
GET {{baseUrl}}/future-purchase
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name future_purchase_projection
GET {{baseUrl}}/future-purchase/projection
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_future_purchase
GET {{baseUrl}}/future-purchase/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_future_purchase
POST {{baseUrl}}/future-purchase
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Notebook",
	"value": 5000,
	"valueAdded": 0,
	"dateAcquisition": "2025-12-31"
}

###

# @name add_value_future_purchase
PATCH {{baseUrl}}/future-purchase/00000000-0000-0000-0000-000000000000/add-value
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"value": 500
}

###

# @name remove_value_future_purchase
PATCH {{baseUrl}}/future-purchase/00000000-0000-0000-0000-000000000000/remove-value
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"value": 200
}

###

# @name delete_future_purchase
DELETE {{baseUrl}}/future-purchase/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
