export const defaultCategories = [
  { title: 'Supermercado', description: 'Compras de alimentos e produtos de higiene' },
  { title: 'Restaurante', description: 'Refeições em restaurantes e lanchonetes' },
  { title: 'Delivery', description: 'Pedidos de comida delivery' },
  { title: 'Padaria', description: 'Pães, bolos e confeitaria' },
  { title: 'Feira', description: 'Frutas, verduras e legumes' },
  { title: 'Açougue', description: 'Carnes e frios' },
  { title: 'Farmácia', description: 'Medicamentos e produtos de saúde' },
  { title: 'Posto de Gasolina', description: 'Combustível para veículos' },
  { title: 'Transporte Público', description: 'Ônibus, metrô e bilhetes' },
  { title: 'Uber/99', description: 'Transporte por aplicativo' },
  { title: 'Manutenção Veicular', description: 'Oficina, troca de óleo e reparos' },
  { title: 'IPVA e Licenciamento', description: 'Impostos e documentação do veículo' },
  { title: 'Estacionamento', description: 'Taxas de estacionamento' },
  { title: 'Aluguel', description: 'Pagamento de aluguel' },
  { title: 'Condomínio', description: 'Taxa condominial' },
  { title: 'Conta de Luz', description: 'Energia elétrica' },
  { title: 'Conta de Água', description: 'Abastecimento de água' },
  { title: 'Gás', description: 'Gás de cozinha' },
  { title: 'Internet', description: 'Provedor de internet' },
  { title: 'Telefone/Celular', description: 'Plano de telefonia' },
  { title: 'Streaming', description: 'Netflix, Spotify e assinaturas' },
  { title: 'Plano de Saúde', description: 'Convênio médico' },
  { title: 'Consultas Médicas', description: 'Médicos particulares' },
  { title: 'Dentista', description: 'Tratamentos odontológicos' },
  { title: 'Academia', description: 'Mensalidade de academia' },
  { title: 'Educação', description: 'Cursos e faculdade' },
  { title: 'Livros', description: 'Compras de livros' },
  { title: 'Material Escolar', description: 'Cadernos, canetas e material' },
  { title: 'Cinema', description: 'Ingressos de cinema' },
  { title: 'Shows e Eventos', description: 'Ingressos de shows e festivais' },
  { title: 'Viagens', description: 'Hospedagem e passagens' },
  { title: 'Hotel', description: 'Hospedagem em hotéis' },
  { title: 'Roupas', description: 'Vestuário e calçados' },
  { title: 'Eletrônicos', description: 'Celulares, computadores e gadgets' },
  { title: 'Móveis', description: 'Móveis e decoração' },
  { title: 'Eletrodomésticos', description: 'Geladeira, fogão e eletrodomésticos' },
  { title: 'Presentes', description: 'Presentes e lembranças' },
  { title: 'Beleza', description: 'Salão, cosméticos e cuidados pessoais' },
  { title: 'Barbearia', description: 'Corte de cabelo e barba' },
  { title: 'Pet Shop', description: 'Produtos e serviços para pets' },
  { title: 'Veterinário', description: 'Consultas e tratamentos para animais' },
  { title: 'Ração', description: 'Alimentação para pets' },
  { title: 'Seguro', description: 'Apólice de seguros' },
  { title: 'Impostos', description: 'IR, IPTU e outros tributos' },
  { title: 'Contador', description: 'Honorários contábeis' },
  { title: 'Advogado', description: 'Honorários advocatícios' },
  { title: 'Doações', description: 'Doações e caridade' },
  { title: 'Dízimo', description: 'Contribuições religiosas' },
  { title: 'Investimentos', description: 'Aplicações financeiras' },
  { title: 'Poupança', description: 'Reserva e economia' },
  { title: 'Salário', description: 'Renda do trabalho' },
  { title: 'Freelance', description: 'Renda de trabalhos avulsos' },
  { title: 'Aluguel Recebido', description: 'Renda de imóveis alugados' },
  { title: 'Dividendos', description: 'Rendimentos de investimentos' },
  { title: 'Reembolso', description: 'Valores devolvidos' },
  { title: 'Empréstimo Recebido', description: 'Dinheiro emprestado recebido' },
  { title: 'Empréstimo Pago', description: 'Pagamento de empréstimos' },
  { title: 'Cartão de Crédito', description: 'Fatura do cartão' },
  { title: 'Financiamento', description: 'Parcelas de financiamento' },
  { title: 'Outros', description: 'Outras despesas ou receitas' },
]
